baseurl: "https://rennerocha.com/"
languageCode: "pt-br"
title: "Renne Rocha"
theme: "hugo-tania"
paginate: 6

params:
  author: "Renne Rocha"
  siteName: "Sharing what I learn about software development mainly"
  siteDesc: "Sharing what I learn about software development mainly"

  colorScheme:
    toggle: true
    default: auto

  maxCategoryToShow: 10

  # Show your social information with icon on index bio with `_index.md` content.
  socialOptions:
    rss: "/index.xml"
    email: "renne@rocha.dev.br"
    github: "https://github.com/sponsors/rennerocha"
    mastodon: "https://chaos.social/@rennerocha"
    peertube: "https://peertube.lhc.net.br/a/rocha/video-channels"

  # Comments settings
  comments:
    enabled: false
    provider: giscus

menu:
  header:
    - name: About Me
      url: "/about-me/"
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "monokai"
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
